### ISSUE TITLE
May be use ":" as redis namespace delimiter?

### ISSUE THREAD

**Issue by xboston** [zhulik/margelet#14]
Docs:
http://redis.io/topics/data-types-intro#redis-keys

> Try to stick with a schema. For instance "object-type:id" is a good idea, as in "user:1000". Dots or dashes are often used for multi-word fields, as in `"comment: 1234:reply.to"` or `"comment:1234:reply-to"`.

https://github.com/resque/redis-namespace 

> namespaced_redis.set('foo', 'bar') # redis_connection.set(`'ns:foo'`, 'bar')

Example:
![2016-04-21 01 07 50](https://cloud.githubusercontent.com/assets/201306/14688808/d0a44742-075d-11e6-80d3-2212a6d79cbe.png)

**Comment by zhulik** [comment]
There is no difference for me, which delimiter use. I'm newbie in Redis. If ":" is default for redis, we should use it. But, this is breaking change, users can lost their date. So, with changing delimiter we should provide some migration script, in readme at least
