### ISSUE TITLE
message.Command() Changed?

### ISSUE THREAD

**Issue by Mrcrypt** [zhulik/margelet#2]
margelet.AddCommandHandler("/cat", CatHandler{})
	margelet.AddSessionHandler("/start", ConfigSessionHandler{})

Should be changed to

	margelet.AddCommandHandler("cat", CatHandler{})
	margelet.AddSessionHandler("start", ConfigSessionHandler{})

because message.Command() seems to return just the command without "/"

**Comment by zhulik** [comment]
@Mrcrypt sorry, tgbotapi's message.Command() does not remove "/". Sources [here](https://github.com/go-telegram-bot-api/telegram-bot-api/blob/master/types.go#L142)

**Comment by Mrcrypt** [comment]
@zhulik  You updated to version 2 "gopkg.in/telegram-bot-api.v2" so it seems like [this](https://github.com/go-telegram-bot-api/telegram-bot-api/blob/v2.2.1/types.go#L134) version is used

```
 func (m *Message) Command() string {
	if !m.IsCommand() {
		return ""
	}

	command := strings.SplitN(m.Text, " ", 2)[0][1:]

	if i := strings.Index(command, "@"); i != -1 {
		command = command[:i]
	}

	return command
}
```

**Comment by zhulik** [comment]
Ooops. You are right. I will update it soon. Thanks!
